### ISSUE TITLE
Inherited roles

### ISSUE THREAD

**Issue by greggilbert** [romanbican/roles#1]
Hey! Great start to a new L5 package. First idea: inherited roles.

Consider you have two roles, Administrator and Editor. An Administrator should be able to do everything an Editor can do. In that case, you'd currently have to do:

`if(\Auth::user()->hasRole('Administrator') || \Auth::user()->hasRole('Editor'))`

which is cumbersome. It'd be easier to just say:

`if(\Auth::user()->hasRole('Editor'))`

Makes sense?

**Comment by romanbican** [comment]
Hello and thank you!

I just pushed a big commit and released first stable version. Now user can have only one role, but there are now permissions. You can look at readme file. I think this problem is solved. If you find another issue, please let me know! Or you can pull request.
