### ISSUE TITLE
How to bypass all permission ?

### ISSUE THREAD

**Issue by andregeges** [romanbican/roles#10]
Hi, this package is awesome.. but sometimes i need to bypass all permission check for debugging. how to achieve that with this package ?

**Comment by romanbican** [comment]
Hello and thanks. I probably understand, but could you please give me an example to be clear? Thanks!

**Comment by andregeges** [comment]
Ok, on every function of my apps i put permission check like

add_post
edit_post
delete_post

now when i still developing my apps, i do not add role permission on my database 
but i put my code to check on my function..  like,

if(! Auth::user()->can('edit_post'))
{
 Session::flash('alert', 'you do not have permission to edit this page')
 return Redirect::back();
}

// code to store to database
----------------------------------------
so for now i want to bypass all permission check on my apps until all feature complete then i put real permission to database and it's my time to check my permission working properly

**Comment by romanbican** [comment]
Well, there is now way how to achieve that at this moment. If you perform a check, it will return false if user has no role or permission.

Do you have any idea, how to implement this feature?

**Comment by andregeges** [comment]
maybe you can check in your method

if( level == x ) return true

and

if (role == 'admin') return true

on every check can() is() level()

sorry i cannot help to code because i still learning to code better

**Comment by romanbican** [comment]
I'll consider it.

**Comment by Kyslik** [comment]
My 2 cents on this is make a config file and make option "pretend" something like Laravel's mailer have.

**Comment by romanbican** [comment]
Done. Please have a look at version 1.5.0.

**Comment by andregeges** [comment]
Wow.. nice..
thanks anyway
