### ISSUE TITLE
how to just 'set' a role

### ISSUE THREAD

**Issue by z1haze** [romanbican/roles#105]
I would like a way to just 'set' the user's primary role, which will remove all attached roles and only set the one i choose.

Is this already easily possible?

**Comment by arafatx** [comment]
$user->detachRoles();//remove all attached roles
$user->detachRole($userRole); //remove specific role
$user->attachRole($adminRole); //set the role you want

is that you want?

**Comment by z1haze** [comment]
More or less yes but attach role and remove role doesn't clear all of them does it ?

**Comment by arafatx** [comment]
Sorry, the detachRole<b>s</b>() doesn't need parameter. Yes it will remove and clear all roles that a user have. While the detachRole($userRole), will only remove a specific role.

**Comment by Namoshek** [comment]
Suggestion: Add a sync-method that allows for replacing all current roles with an array of new roles, similar to the existing sync-methods for Laravels relations. Could also be implemented for all other parts of the plugin, e.g. permissions.
