### ISSUE TITLE
Role Creation Failed due to ReflectionException

### ISSUE THREAD

**Issue by MHassanSaqib** [romanbican/roles#106]
Hi, I am trying to create roles by using following code.

<?php

use Bican\Roles\Models\Role;

use Illuminate\Database\Seeder;

class RoleTableSeeder extends  Seeder
{
    public function run()
    {
    $adminRole = Role::create([
        'name' => 'Admin',
        'slug' => 'admin',
        'description' => '', // optional
        'level' => 1, // optional, set to 1 by default
    ]);
    }
}

and I am seeding it using following command on CLI.

php artisan db:seed --class=RoleTableSeeder

but unfortunately I am getting ReflectionException "[ReflectionException]
Class RoleTableSeeder does not exist"... 

What might be wrong with it? Looking for your help...

**Comment by romanbican** [comment]
composer dump-autoload

**Comment by MHassanSaqib** [comment]
Thank you... My problem solved...
