### ISSUE TITLE
funtion IS() not working

### ISSUE THREAD

**Issue by nasatome** [romanbican/roles#11]
Hi, I am beginner in Laravel, I hope you can help me,
I create my Virtual Host and named http: //laravel.app
I install Laravel:

```
  composer create-project laravel/laravel --prefer-dist
```

This installs me Laravel 5

I go to my composer.json file and add:

```
   "bican/roles": "1.3.*"
```

I run in console:

```
  composer update
```

in config/app.php : Providers add

```
    'Bican\Roles\RolesServiceProvider',
```

I do migration
```
php artisan vendor:publish
```
```
php artisan migrate
```

in app/user.php  I still like this:
```
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Bican\Roles\Contracts\HasRoleContract;
use Bican\Roles\Contracts\HasPermissionContract;
use Bican\Roles\Traits\HasRole;
use Bican\Roles\Traits\HasPermission;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract, HasRoleContract, HasPermissionContract {

	use Authenticatable, CanResetPassword, HasRole, HasPermission;
	/**
```

and this is where I have doubts:

I edit routes.php an add  a new route Controller called users
```
app/Http/routes.php
```
I add this:
```
Route::controllers([
	'users' => 'UsersController', //add here
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
```

in app/Http/Controllers

create a new file called:
```
//UserController.php
<?php namespace App\Http\Controllers;
use Bican\Roles\Models\Role;
use App\User;
use App\Funciones;

class UsersController extends Controller{
   public function getIndex()
    {
       $role = Role::create([
              'name' => 'Admin',
              'slug' => 'Admin',
              'description' => '' 
          ]);

          User::find(1)->attachRole($role);
    }
}
```
Added a new Member Since:
```
http://laravel.app/auth/register
```
Now I run
```
http://laravel.app/users
```

and in my database so good, in the table "ROLE_USER"
```
 appears: id: 1, role_id: 1, user_id:1 created_at_ :2015-xxxxxxx  etc
```

after I delete content  in getIndex()
and I substitute
```
$user = User::find(1);
if ($user->is('admin')) // or you can pass an id
{
    return 'admin';
}
```
Now I run newly
```
http://laravel.app/users
```
But the function is() me always returns false, and look at your code and not defined any function IS ()

Temporarily I created this function:
```
  public function ComprobarRol()

    {

        $result = \DB::table('users')
            ->select('users.first_name', 'roles.name as RoldeSistema')
            ->where('users.id','=','1')
            ->join('role_user','users.id','=','role_user.user_id' )
            ->join('roles','role_user.role_id','=','roles.id' )
            ->get();
        var_dump($result);
        var_dump($result [0]->name);
        var_dump($result [0]->RoldeSistema);

    }
```

I returns the user name and the name of the role in the system, I hope you can help me
as I do for the IS function () function?

where I have to create code ?, or dependencies have to add?

**Comment by romanbican** [comment]
Hi,
I was following steps you describe and at the end, it works for me.

```php
$user = User::find(1);
if ($user->is('admin')) // or you can pass an id
{
    return 'admin';
}
```

This check returns `true` to me. So I don't know what is the problem for you.

**Comment by nasatome** [comment]
![error in is](https://cloud.githubusercontent.com/assets/3455076/6234813/44549dac-b6a3-11e4-97d9-fdc7de4a8bf4.png)

![2015-02-17 12_49_09-localhost _ uniform server _ agenciabs _ roles _ phpmyadmin 4 3 8](https://cloud.githubusercontent.com/assets/3455076/6234866/9a55d9c8-b6a3-11e4-9b70-98bbbc21d695.png)
![2015-02-17 12_49_30-localhost _ uniform server _ agenciabs _ role_user _ phpmyadmin 4 3 8](https://cloud.githubusercontent.com/assets/3455076/6234868/9a5dc75a-b6a3-11e4-8aed-c8a60feff4b1.png)
![2015-02-17 12_50_31-localhost _ uniform server _ agenciabs _ users _ phpmyadmin 4 3 8](https://cloud.githubusercontent.com/assets/3455076/6234867/9a57db38-b6a3-11e4-9fe2-1a59bf4a9fbe.png)


($ User-> is ('admin')) there says he can spend this refers ID? 

 .... and there is the error I get, any ideas?
you work in laravel 5.0 or 5.0.1?
 sorry for my bad English

**Comment by romanbican** [comment]
Ignore error from PhpStorm.

Try this check:
```php
$user = User::find(1);
if ($user->is('administrator')) // or you can pass an id
{
    return 'admin';
}
```
Argument must be `id` or `slug` (slug is without upper letters and spaces)!

**Comment by nasatome** [comment]
Ooooh thanks!!! slug is the argument, work it!!   I thought it was the Argument was name, 
and my error is a uppercase Administrator to administrator.

excellent plugin, very easy to use for a beginner like me and functional.

Now I do not need but is there any way to check the level?

**Comment by romanbican** [comment]
Yes, there is!

```php
$user = User::find(1);

echo $user->level();
```

For more info, please read readme file.

Closing.
