### ISSUE TITLE
Trait collision on migration

### ISSUE THREAD

**Issue by ghost** [romanbican/roles#110]
```
[Symfony\Component\Debug\Exception\FatalErrorException] Trait method can has not been applied, because there are collisions with other trait methods on App\User 
```

I spun up a new install of Laravel 5.1.11 which is now using Authorization, and when I run my migration I receive the error above. I commented out all the bican\roles traits and contracts and it allowed me to migrate.

It looks like the collision is happening between:

```
use Bican\Roles\Traits\HasRoleAndPermission;
```

and

```
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
```

Seems that the Authorizable interface has a 'can' method as well.

Authorizable:

```
    /**
     * Determine if the entity has a given ability.
     *
     * @param  string  $ability
     * @param  array|mixed  $arguments
     * @return bool
     */
    public function can($ability, $arguments = []);
```

HasRoleAndPermission:

```
    /**
     * Check if the user has a permission or permissions.
     *
     * @param int|string|array $permission
     * @param bool $all
     * @return bool
     */
    public function can($permission, $all = false)
    {
        if ($this->isPretendEnabled()) {
            return $this->pretend('can');
        }

        return $this->{$this->getMethodName('can', $all)}($permission);
    }
```

**Comment by vahobrsti** [comment]
Try this one in your User.php model. Pay attention to insteadof keyword

```
class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract{
    use Authenticatable, CanResetPassword, HasRoleAndPermission { 
HasRoleAndPermission ::can insteadof Authorizable;
}

```

**Comment by zoranlorkovic** [comment]
Yes. I also have this problem. It seems that this package isn't full compatible with new version of Laravel 5.1 (from 5.1.11) as there were some changes to Authorization, mention above.

**Comment by ghost** [comment]
@vahobrsti I could see that working, but it is a work around if you want to use both Authorizable as well as Bican/Roles

**Comment by chrisburton** [comment]
Will this be fixed in the near future? Perhaps renaming `can` to `may`?

**Comment by mxrtos** [comment]
vahobrsti's solution works, but you would have to choose between one or the other "can" implementation. So this is why I agree with christopherburton on renaming can to may.
Regards.

**Comment by commandantp** [comment]
The work around worked, but +1 for the PR to change 'can' in 'may'

**Comment by gustoase** [comment]
+1

**Comment by Ugluth** [comment]
+1, any update on this? Is it going to be implemented?

**Comment by jgardezi** [comment]
+1 any work on this issue to make it compatible with Laraval 5.1.

**Comment by jaumeavila** [comment]
Something new about it?

**Comment by ghost** [comment]
Repository hasn't been active in quite some time, clearing out old issues. Closing this out.
