### ISSUE TITLE
Middleware with Route Resource but only certain methods

### ISSUE THREAD

**Issue by chrisburton** [romanbican/roles#116]
Had this issue just now. Posting here in case anyone needs it. 

**Note:** The order is important.

**Update:** I wanted to also note that apparently resource routes do not accept middleware as an option. This requires you to use a group route for this functionality.

``` php
Route::group(['middleware' => 'role:admin'], function() 
{
    resource('articles', 'ArticlesController', ['only' => ['create', 'store', 'edit', 'update', 'destroy']]);
});

Route::resource('articles', 'ArticlesController', ['only' => ['index', 'show']]);
```

**Comment by n0Sp00n** [comment]
create, store, edit are these permissions?  I wonder if I have to put
permissions for each action in my site.

**Comment by chrisburton** [comment]
@n0Sp00n No. These are methods for a typical resource controller.
