### ISSUE TITLE
Does not return roles when User primary key is not "id"

### ISSUE THREAD

**Issue by KalebClark** [romanbican/roles#117]
I am not getting any functionality with this package, and I think its because my PK is "user_id" instead of "id" in my user model.

Does this seem right?

Thanks,
-Kaleb

**Comment by chrisburton** [comment]
Can you provide code?

**Comment by KalebClark** [comment]
Just figured this out. My error...

Thanks for getting back so quickly though!

-Kaleb

**Comment by chrisburton** [comment]
@KalebClark You should provide the solution in case anyone else has the same problem.
