### ISSUE TITLE
App\User cannot implement Bican\Roles\Traits\HasRoleAndPermission - it is not an interface

### ISSUE THREAD

**Issue by bituka** [romanbican/roles#118]
I am trying to attach a role. I am having error below. 

FatalErrorException in User.php line 21:
App\User cannot implement Bican\Roles\Traits\HasRoleAndPermission - it is not an interface

**Comment by alvioleegia** [comment]
There is a mistake in documentation, it's solved by replacing:
`use Bican\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;`
with
`use Bican\Roles\Contracts\HasRoleAndPermissionContract;`

**Comment by bituka** [comment]
Thanks! I'll try this if decided to add this package again, Currently trying Laravel's Authorization for now.
