### ISSUE TITLE
in which file can i create roles?

### ISSUE THREAD

**Issue by RachidBourougaa** [romanbican/roles#126]
I downloaded for the first time this package, and i didn't understood how to use it.
In which file i can create roles and how can i add a role to an user ?

Sorry, i'm a novice.

**Comment by martiendt** [comment]
Please checkout the user guide here :  https://github.com/romanbican/roles/blob/master/README.md

To create a role you can use this code

```
$adminRole = Role::create([
    'name' => 'Admin',
    'slug' => 'admin',
    'description' => '', // optional
    'level' => 1, // optional, set to 1 by default
]);
```

and if you want to attach this role to the user you can use this code

```
use App\User;

$user = User::find($id);

$user->attachRole($adminRole); // you can pass whole object, or just an id
```

**Comment by RachidBourougaa** [comment]
Thank you very much.
