### ISSUE TITLE
strange error when attempting to attach role

### ISSUE THREAD

**Issue by z1haze** [romanbican/roles#127]
Hi, I have used this package in the past for permissions and didnt have any issue, but now for whatever the reason is Im getting BadMethodCallException with message 'Call to undefined method Illuminate\Database\Query\Builder::attachRole()' while trying to attach a role to a use. Im just in artisan tinker. Please let me know what I could be doing wrong?

**Comment by z1haze** [comment]
Nevermind, please disregard. Was a combination of not having the correct contracts and that conflict with the traits. but I fixed it.

**Comment by flakerimi** [comment]
@z1haze close this then.
