### ISSUE TITLE
How atach roles when registering user 

### ISSUE THREAD

**Issue by texnika01** [romanbican/roles#128]
How atach roles when registering user 
<----------->
use Bican\Roles\Models\Role;

public function postRegister(Request $request, $id)
    {
        $this->validate($request, [
            'email' => 'required|unique:users|email|max:255',
            'username' => 'required|unique:users|alpha_dash|max:20',
            'password' => 'required|min:6',
        ]);
        //dd('all OK');
        $user = User::create([
            'email' => $request->input('email'),
            'username' => $request->input('username'),
            'password' => bcrypt($request->input('password')),
        ]);
        $user = User::find($id);
        $user->attachRole(3);

```
    return redirect()
        ->route('home')
        ->with('info','Your account has been createand you can sign in');
}
```

<----->

**Comment by mikhi** [comment]
sorry, i dont understand. it is an question or an example of how to attach a role to user?

**Comment by texnika01** [comment]
how attach a role to register user
