### ISSUE TITLE
proposal: a shorthand to use in blade

### ISSUE THREAD

**Issue by UnrulyNatives** [romanbican/roles#14]
Hi, 
your package works great and (short of DB-supported translations) it makes it possible for me to migrate from L4 finally, but...

is there a way of using in BLADE conditions such as:

    @if (Auth::user()->is('Admin'))

without a need to create any $user variable?
I'd be happy to see an elegant solution for the issue. 

What I do now is to define a $user variable in each method with this command:

    $user = User::find(Auth::id());

I tried to add the varaible controller-wide

    public function __construct()
    {       
    $user = User::find(Auth::id());   
    View::share('user', $user); // Share $user with all views
    }
but it doesn't work to me. :(

Thanks again.

**Comment by romanbican** [comment]
Hi,
you always need to have User object. If we're talking only about Blade, you can take advantage of [view composers](http://laravel.com/docs/5.0/views#view-composers) in Laravel 5.

Then you can have something like this:

```php
@if ($currentUser->is('admin'))
    //
@endif
```

Instead of this:

```php
@if (Auth::user()->is('admin'))
    // something
@endif
```

But if I understand correctly, you want something like this?

```php
@role ('admin')
    // something
@endrole

@permission ('edit_articles')
    // something
@endpermission
```

Please, specify me your vision :-).

**Comment by romanbican** [comment]
There is also a very nice [video](https://laracasts.com/series/laravel-5-fundamentals/episodes/25) about view composers in Laravel 5. Have a look!

**Comment by UnrulyNatives** [comment]
This solution would be amazing:

    @role ('admin')
        // something
    @endrole

The below made me perfectly happy:

    @if (Auth::user()->is('admin'))
       // something
    @endif

What I was unable to do in my L4 solution was using multiple conditions. I just user &&
Can you give me an example of a syntax for sth like this:

     @if (Auth::user()->is('admin') && Auth::user()->is('Developer'))

desired solution would be sth like this: 

    @if (Auth::user()->is('Admin','Developer') 

After you answer I will prepare a pull request with all working examples you have provided. My pleasure.

**Comment by romanbican** [comment]
There is a way to check for multiple roles or permissions in one condition in my package.

```php
if ($user->is('admin|moderator')) // or $user->is('admin, moderator') or $user->is(['admin', 'moderator'])
{
    // if user has at least one role
}

if ($user->is('admin|moderator', 'all')) // or $user->is('admin, moderator', 'all') or $user->is(['admin', 'moderator'], 'all')
{
    // if user has all roles that we check for
}
```
The same syntax applies to permissions.

Later today, I'll be working on this syntax:

```php
@role ('admin')
    // something
@endrole
```

**Comment by romanbican** [comment]
New release is out. Check it out. There are some changes.
