### ISSUE TITLE
You don't have a required ['admin'] role.

### ISSUE THREAD

**Issue by kzorluoglu** [romanbican/roles#148]
Hi Everyone, I have this error message, 

```
RoleDeniedException in VerifyRole.php line 42:
You don't have a required ['admin'] role.
```

but I think I have everything set up properly..

Example my tables;
**role** _table_
id name slug description level created_at updated_at
1 Admin admin 1 2016-02-16 19:50:31 2016-02-16 19:50:31

**role_user** _table_
id role_id user_id created_at updated_at
1 1 1 2016-02-16 20:14:30 2016-02-16 20:14:30

*_routes.php *_

```
Route::get('/admin', [
    'as' => 'admin',
    'middleware' => 'role:admin',
    'uses' => 'LoginController@index',
]);
```

what is wrong?

**Comment by mackhankins** [comment]
Do you have the admin role in the database?  I use this seed to give myself admin.

``` php
class AdminTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Role::create([
            'name' => 'Admin',
            'slug' => 'admin',
            'level' => '5',
        ]);
        $user = User::find('1');
        $user->attachRole('1');
    }
}
```

**Comment by kzorluoglu** [comment]
installation was wrong. I installed again, he was restored, 
Thanks
