### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by UnrulyNatives** [romanbican/roles#15]
the blade extension

    @role('admin') // @if(Auth::check() && Auth::user()->is('admin'))

is cool, but sometimes I want to use IF ELSE statement to show different content to a logged admin,and another to everybody else.
Can you design statement which would combine the two conditions (and mean "logged Admin")?
maybe sth like this

    @if(Auth::check()->is('Admin'))

Peter

**Comment by romanbican** [comment]
Well, if I understand correctly, you can do something like this:

```php
@role('admin')
    // user is logged in and has admin role
@elseif(Auth::check())
    // user is logged in but has not admin role
@else
   // user is not logged in
@endrole
```

Is this a solution? If not, please give me an example.

**Comment by UnrulyNatives** [comment]
Yes, this is the solution!
