### ISSUE TITLE
Banning users and redirect them to a specific page.

### ISSUE THREAD

**Issue by RosiersRobin** [romanbican/roles#158]
Hi,

I was wondering, how I could ban people via this package...

So I'm currently using Laravel **5.1** and I'm trying to 'ban' users from my site.
I have a table called 'banned' wich has the following tructure:
[http://laravel.io/bin/KkKRK](http://laravel.io/bin/KkKRK)

I also have the standard structure of the roles (bican roles).

Now, I want to be able to display a custom banned view to my banned users with the data from inside the 'banned' table.

What would be the best way to do this?

**Comment by Isfirs** [comment]
If they can still log in (Hint: Maybe a security issue if they can?) You could create a middleware on the `web` stack and in that you check if the user has the `banned` role (or permission?).

**Comment by RosiersRobin** [comment]
Found the thing. They MUST be able to log in :p Since they need to see the reason why they are banned etc... But, I found the solution.

**Comment by Isfirs** [comment]
Maybe you will post your attempt so future users reading this will have an idea?

**Comment by RosiersRobin** [comment]
I added a new middleware class:

``` php
<?php

namespace App\Http\Middleware;

use Closure;
use Auth;
use App\User;
use DB;
use Carbon\Carbon;

class CheckBanMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (Auth::check()) {
                if (User::CheckBan()) {
                    $bandata = DB::table('banned')->where('user_id', '=', Auth::id())->where('lifted', '=', Null)->where('expires', '>=', Carbon::now())->first();
                    return response()->view('banned', ['bandata' => $bandata]);
                }
        }
        return $next($request);
    }
}
```

Then in User.php added this static function:

``` php
public static function CheckBan()
    {
        return DB::table('banned')->where('user_id', '=', Auth::id())->where('lifted', '=', Null)->where('expires', '>=', Carbon::now())->exists();
    }
```

And added my middleware in the Kernel.php

`protected $middleware`

**Comment by Isfirs** [comment]
Wouldn't it be easier using the `bican/roles` functions since we are talking in that project?

Pseudocode:

```
if (\Auth::check() && !isRoute('banned')) {
    if(\Auth::user()->hasPermission('banned')) {
        return redirect()->route('banned');
    }
}
```

Not sure, if you need \Auth::check() when you apply this to your àuth` stack, because that will automaticly make sure you **are** logged in and **have** a user instance.

**Comment by RosiersRobin** [comment]
I just wanted to display a new view, since I like to keep the URL.
