### ISSUE TITLE
Choose table

### ISSUE THREAD

**Issue by mybigman** [romanbican/roles#16]
Hi,

Can you add a config file that allows specifying the database to get roles/permissions from.

thanks

**Comment by romanbican** [comment]
Hi,
you mean table names?

**Comment by mybigman** [comment]
@romanbican nope the actual database.

As it stands it will read what database is used from the Config/database.php file.

We have approximately 50 databases and in the above config we have a generic database only for the purpose of the config which has no tables.

So a config file to specify which DB would be ideal or some how i have to dynamically tell it which DB to connect to every time it runs.

thanks

**Comment by romanbican** [comment]
Ok, if you want, submit a pull request and I'd be glad to push it.

**Comment by romanbican** [comment]
Done. Have a look at version 1.5.0.

**Comment by mybigman** [comment]
champ... i shall check it out :)
