### ISSUE TITLE
How to config user table name?

### ISSUE THREAD

**Issue by guoyunhe** [romanbican/roles#167]
Since some reasons, my user table is named `user` rather than `users`. How could I change the table name in `config/roles.php`?

**Comment by tripathi-swapnil** [comment]
No need to do it there. just add `user` table name in your model. You need to add   protected $table = 'user';

**Comment by tflori** [comment]
Yeah, have the same problem. This question is open since april 2016 I'm afraid it will not be solved..

App:
```php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {
  protected $table = 'admintool_users';
}
```

config/auth.php:
```php
return [
  // what ever else
  'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ]
  ]
];
```

When I run migrate I get the following error:
```bash
php artisan migrate
#  [Illuminate\Database\QueryException]                                                                                                       
#  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `role_user` add constraint `role_user_user_id_fo  
#  reign` foreign key (`user_id`) references `users` (`id`) on delete cascade) 
```

**Comment by tflori** [comment]
I solved it by changing it in database/migrations/... but we can also read the config there - so I don't know why not to use it..
