### ISSUE TITLE
Get all permissions for user.

### ISSUE THREAD

**Issue by Kyslik** [romanbican/roles#17]
How does one acquire all permissions for user.

I used:

    $user->with('roles')->get(); //gets me all roles for user
    $user->with('permissions')->get(); //throws error Eloquent\Collection::addEagerConstraints()

If anyone wonders I want to be able to show all permissions per user in administration.

**Comment by romanbican** [comment]
If you want all permissions for user, just call permissions method.

```php
$permissions = $user->permissions();
```

We can't eager load it, because this method will return Collection. I know this is not the best solution, so I will be working on it in the next version.
