### ISSUE TITLE
Laravel 5.2 User model? 

### ISSUE THREAD

**Issue by kzorluoglu** [romanbican/roles#173]
Hi Everyone,
i use this package with Laravel 5.2
I added lines in to the User.php

```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Bican\Roles\Traits\HasRoleAndPermission;
use Bican\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;

class User extends Authenticatable implements HasRoleAndPermissionContract
{
    use HasRoleAndPermission;

    protected $fillable = [
        "name", "email", "password",
    ];

    protected $hidden = [
        "password", "remember_token",
    ];

}

```

and on controller for if question..

```
      $user = \App\User::find(Auth::id());
       if ($user->is('admin')) { // you can pass an id or slug
        return redirect('login');
      }
```

but not running. Where is the error?
Thanks

**Comment by gerardojbaez** [comment]
Same here! If I call `$user->getRoles()` I get `null` but `$user->roles` works properly.

UPDATE
I've placed `dd($this->roles)` and `$this->roles()->get()` inside the `getRoles()` function and are returning `null`.

**Comment by CristianFodor** [comment]
korayzorluoglu I've had the same problem. In controllers and in models I couldn't identify role by role name, so I had to do it trought slug or id.

`if ($user->is(1)) { // pass role id
            return redirect('login');
        }`

 `if ($user->is('admin')) { // pass slug, but make sure that it's not the same with the role name
            return redirect('login');
        }`

**Comment by 02-web** [comment]
+

**Comment by muneebarif11** [comment]
I'm on laravel 5.1 and  I'm able to get roles of Authenticated user but can't get roles of any other user... i was able to do so by getRoles() method and roles() returns null. I any buddy found solution plz comment

**Comment by CristianFodor** [comment]
Try something like this:

> $users = User::all();
> $foreach($users as $user){
> $user->getRoles();
> }

If this is what you need.

**Comment by johannesschobel** [comment]
maybe this issue is related to #183 ?
