### ISSUE TITLE
@role('admin')

### ISSUE THREAD

**Issue by dailez** [romanbican/roles#18]
Am I wrong or checks this blade statement whether the name of the role is 'admin'. I though it should be the slug!?

**Comment by romanbican** [comment]
It checks for a slug.

**Comment by dailez** [comment]
Could you please check that? I don't think so. Kindest regards

**Comment by romanbican** [comment]
Yeah, it is working. It checks for a slug or id.

**Comment by dailez** [comment]
You are right. It is working perfectly fine. My fault, I mixed up the if/else statements.
