### ISSUE TITLE
ErrorException in HasRoleAndPermission.php line 104

### ISSUE THREAD

**Issue by wstudios** [romanbican/roles#187]
I am using laravel 5.3, I added the fixes in the pull requests so everything works great. The issue I have is when applying a role middleware to a route.

I am using this:
`Route::group(['prefix' => 'office', 'middleware' => 'role:admin'], function()`

It however throws the above error, here is some more on the error.

`at HandleExceptions->handleError('8', 'Trying to get property of non-object', '......./vendor/bican/roles/src/Bican/Roles/Traits/HasRoleAndPermission.php', '104', array('key' => object(Role), 'value' => '0', 'role' => 'admin')) in HasRoleAndPermission.php line 104`

Thanks for any help.

**Comment by nikolaynesov** [comment]
@wstudios [#189](https://github.com/romanbican/roles/pull/189)
this should be the fix. Let me know if you still have any problems.

**Comment by wstudios** [comment]
Thank you! Applying the fixes works great.
