### ISSUE TITLE
How I can get all users which have Role admin

### ISSUE THREAD

**Issue by reda1987** [romanbican/roles#206]
How I can get all users which have Role admin

find the solution 

Auto apply to bolde.php

@php $supporter = \Bican\Roles\Models\Role::where('slug', 'supporter')->first()->users()->where('users.id','!=',Auth::user()->id)->pluck('users.name','users.id')->toArray(); @endphp
you can use
Role::where('slug', 'supporter')->first()->users()
OR
Role::find($id)->users()

**Comment by mohamedredaibrahim** [comment]
Auto apply to bolde.php

@php $supporter  = \Bican\Roles\Models\Role::where('slug', 'supporter')->first()->users()->where('users.id','!=',Auth::user()->id)->lists('users.name','users.id')->toArray(); @endphp
you can use 
Role::where('slug', 'supporter')->first()->users()
OR
Role::find($id)->users()
