### ISSUE TITLE
user can() from role or direct from user

### ISSUE THREAD

**Issue by andregeges** [romanbican/roles#22]
Hi, my company manage a lot of user,
my manager needs to know this user had permission access from role or from user.. 
for example, when some permission attach direct to user 
i need to check like this : 

$user->canFromUser() // return true

$user->canFromRole() // return false

how to achieve this ?

**Comment by Kyslik** [comment]
Take a look at this function https://github.com/romanbican/roles/blob/master/src/Bican/Roles/Traits/HasRoleAndPermission.php#L209 might give you some insight.

**Comment by romanbican** [comment]
I'll look at it soon.

**Comment by romanbican** [comment]
And it's finally done. Sorry for delay. Have a look at ``can`` method. There is new argument ``from``. You can leave it blank or you can pass "role" (permissions from roles) or "user" (permissions that are attached directly to the user). Hope it makes sense.
