### ISSUE TITLE
Feature proposal - list roles

### ISSUE THREAD

**Issue by UnrulyNatives** [romanbican/roles#25]
In order to list all roles of a current user I came up with crude, ugly solution:
I just list all of them like that:
	@role('Admin')  
	   	<span class="ui label">Admin</span>
	@endrole

But in one of my project I will soon have more than 20 roles. 
Are you planning any feature which would list all roles of the current user?

If yest, it should include a way to style each role with a css, such as this one:

 {!! 

                    join(', ',
                        array_map(function($o) {
                            return link_to_route('roles',
                            $o->name,
                            [$o->id],
                            ['class' => 'ui blue tag label']
                            );}, 
                            $object->capacities->all())
                ) !!}

Thx

**Comment by Kyslik** [comment]
I think it should return collection so developer can do whatever with data not just show them...

**Comment by romanbican** [comment]
```php
@foreach (Auth::user()->roles()->get() as $role)
{{ $role->name }}
@endforeach
```

**Comment by UnrulyNatives** [comment]
Your code works perfectly! Thank you. 
I suggest you include it in your readme.md.

Peter

**Comment by romanbican** [comment]
Yes, thanks.
