### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tnrn9b** [romanbican/roles#27]
This package seems great. I am new to Laravel. I was wondering where to implement the 

<code> 
<p> use Bican\Roles\Models\Role;</p>
<p> use App\User; </p>
$role = Role::create([
  <p>  'name' => 'Admin', </p>
 <p>   'slug' => 'admin',</p>
   <p> 'description' => '' // optional </p>
]) </code>

Would I use this inside roles.php? Sorry, I know this isn't an 'issue' per se; but, I really want to use this package in an upcoming project.

**Comment by janareit** [comment]
@tnrn9b You can use database seeders for seeding your desired roles/permissions after you have created your migrations. (btw: those you can ```artisan vendor:publish```). Create RolesAndPermissionsInitSeeder.php for example and set your config there.
