### ISSUE TITLE
php artisan vendor:publish always copies migrations

### ISSUE THREAD

**Issue by danieliancu** [romanbican/roles#33]
First of all, let me say thanks for this great L5 package. The Blade Extensions are wonderful.

I noticed that running `php artisan vendor:publish` always outputs:

    Copied Directory [/vendor/bican/roles/src/migrations] To [/database/migrations]

But looking in the migrations directory it didn't changed anything.

**Comment by romanbican** [comment]
Hi, thanks.

It works for me. I don't know where the problem is for you.

**Comment by danieliancu** [comment]
I am able to reproduce the error on a fresh install of L5. This is the only package I added.

**Comment by romanbican** [comment]
I don't know, but it works for me. I tried it again.

**Comment by danieliancu** [comment]
I can still reproduce the error on a fresh homestead, please let me know if you require more information.

**Comment by romanbican** [comment]
Yes, please.
