### ISSUE TITLE
Roles and permissions as middleware like Laravel Auth

### ISSUE THREAD

**Issue by visualight** [romanbican/roles#36]
Hello,

My Laravel project work with two controller (1 for the users and 1 for the admin).
I defined roles for users and admin. But if i log me in such as a user i can acces to the admin page.

It will be fine to define roles and permissions as middelware to call this in the controller like this

```php
public function __construct()
{
        $this->middleware('auth');
        $this->middleware('roles')->is('admin')
}
```

So i can restric all method in my controller for role: admin only.

Do you know a other solution ?

Thank you

**Comment by romanbican** [comment]
Well, in Laravel 5.1, there will be middleware parameters. So it will be really simple.

https://d1zj60nuin5mrx.cloudfront.net/media/2015/02/24125618/middleware-parameters.png

**Comment by zlorkovic** [comment]
I'm also interested in this option.
What is best solution before Laravel 5.1 goes out?

**Comment by romanbican** [comment]
Well, I think you must have middleware for every role.

**Comment by interphased** [comment]
I had a project that I needed to do this with and found it easy to set it up where it would redirect a response if you were not a certain role, and then use them one after the other. So I have `redirectIfNotAdmin`, `redirectIfNotApplicant`, etc.

```
public function __construct()
	{
		$this->middleware('auth');
		$this->middleware('admin', ['except' => ['index', 'show']]);
		$this->middleware('applicant', ['only' => ['something', 'somethingElse']]);
	}
```

```
class RedirectIfNotAdmin {
	public function handle($request, Closure $next)
	{
		if (Auth::user()->is('admin'))
		{
			return $next($request);
		}

		return redirect()->route('dashboard')
			->with('flash_message', 'Sorry, you do not have enough privileges to view that page.');
	}
}
```

Works for me until Laravel 5.1 comes out.
