### ISSUE TITLE
All users with Permission

### ISSUE THREAD

**Issue by sniper7kills** [romanbican/roles#37]
I'm trying to get all users who have a permission; and I'm sure I'm doing something stupid.

    dd(User::whereHas('permissions', function($q)
    {
        $q->where('slug', 'page.owner');
    })->get());

returns the following error:

    FatalErrorException in Builder.php line 564:
    Call to undefined method Illuminate\Database\Eloquent\Collection::getRelationCountQuery()

I would do 

    Permission::where('slug','page.owner')->get()->users

But I need to also get the users who are inheriting this permission from lower level roles.

**Comment by romanbican** [comment]
You must write far more complex query to fetch that. This package can't help you much. Have a look at rolePermissions and userPermissions methods.

**Comment by itsazzad** [comment]
You may try this:

`DB::table('users')
					->join('role_user', function($join)  use ($role_id)
					{
						$join->on('users.id', '=', 'role_user.user_id')
								->where('role_user.role_id', '=', $role_id);
					})
					->select('users.id', 'users.name');`

**Comment by ascito** [comment]
this code works, but is optimal?

`$users = User::with('roles')->whereHas('roles', function($q)
        {
           $q->whereIn('name', ['admin']);
        })->get();`
