### ISSUE TITLE
1 excludes from the right to inherit the Roles

### ISSUE THREAD

**Issue by ngoclanbaby86** [romanbican/roles#38]
![untitled-1 copy](https://cloud.githubusercontent.com/assets/7061835/7786978/96960010-021b-11e5-8250-8df0fed996eb.jpg)
exclude one or more rights to inherit from Roles, eg admin group have permission to create, edit, delete. but I added one person and only the admin group permission to create, edit, and right to left will not be inherited. (this is just an example understandable)

Then you've come to think this case has not, please help me. many thanks.
PS: I think that the Sentry 2 supports very good but it does not yet support Laravel 5 for the moment

**Comment by romanbican** [comment]
You must handle it alone. This is too much specific for your application.

**Comment by sniper7kills** [comment]
@ngoclanbaby86 I just made a pull request #42 with what I believe you are looking for. Be warned it is not directly compatible with the package for an upgrade.
But would allow you to deny a permission to a user, as well as simply assigning it to them. The Inherit option would be basically useless as permissions are inherited by default. So detaching the permission from the user would be equivalent to setting it to inherit.

**Comment by dustingraham** [comment]
@romanbican Actually, the general concept is good I think. The ability to add a user to a role, but then specifically deny a particular permission that would have otherwise been inherited.
