### ISSUE TITLE
issue after upgrade to Laravel 5.1

### ISSUE THREAD

**Issue by UnrulyNatives** [romanbican/roles#46]
Hi,
I got this errors after upgrading to L5.1: 

FatalErrorException in RolesServiceProvider.php line 47: Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()

My friend adviced me to download & use ZIP file with your package instead of using composer and it helped. 

How about a new release to fix this issue?

**Comment by romanbican** [comment]
Laravel 5.1 is not out yet. If you want to use it anyways, please pull in dev-master.

**Comment by bryannielsen** [comment]
I'm seeing this now in the official 5.1 release, is a tagged release coming soon?
