### ISSUE TITLE
Auth::user()-is() not working

### ISSUE THREAD

**Issue by zlorkovic** [romanbican/roles#48]
Hi,

Why Auth::user()->is('role'), not working, but I need to catch user by id
(something like $user = User::find(Auth::user()->id);
Then, $user->is('role') is working.

**Comment by romanbican** [comment]
Are you logged in? What's the error?

**Comment by zlorkovic** [comment]
Yes, I'm logged it.
There is no error displayed, I just got false when I check `Auth::user()->is('role')`.
While I use something like this:
`$user = User::find(Auth::user()->id);`
`$user->is('role');`
returns true.

It's like Auth::user() doesn't catch relation between user and role.

**Comment by romanbican** [comment]
It is working.

**Comment by szabizs** [comment]
@zlorkovic  it is working, you first have to check if you are logged in.

`@if(Auth::user() && Auth::user()->is('foo.bar'))`
