### ISSUE TITLE
Check if user created the post

### ISSUE THREAD

**Issue by WillyReyno** [romanbican/roles#49]
Hi !

I wanted to know if there was a simple way with this package to check if a user was assigned to an article/profile/whatever? I think it could be done with permissions.

For example, if the user is on its own profile, is there a way to put a custom message in the blade template?
Or something similar if the user is the author of some article on a blog ?

For the moment I'm checking like this and I'm pretty sure that's not the best way :
if(Auth::user()-> id == $event->user_id)

Thank you very much,

**Comment by romanbican** [comment]
Is this what you want? https://github.com/romanbican/roles#entity-check

**Comment by WillyReyno** [comment]
I don't really understand where I must put the $user->attachPermission ? Is it on creating an article for example ?

**Comment by romanbican** [comment]
Well, you must have something like admin panel where you can attach roles and permissions.

**Comment by WillyReyno** [comment]
Okay, I made it work for articles. 

But I still can't use it on the user profile.

I put this in my seeders :

![permissiontableseeder2](https://cloud.githubusercontent.com/assets/5576482/8013959/fe73ecdc-0bcc-11e5-98d7-240a649b6710.PNG)

And in my view I put : 

![blade](https://cloud.githubusercontent.com/assets/5576482/8013964/07727754-0bcd-11e5-96dc-c5a282495dec.PNG)

I tried logging in with an user, and whatever the profile I'm looking (my own or someone else's), the "test" is showing. I just want it to be displayed on my own profile page.

By the way, thank you for helping me, I'm not really at ease with Laravel for the moment.

**Comment by romanbican** [comment]
So, now I understand. I'll explain you.

If you want a user to edit all articles, give him permission edit.articles. Then he can edit all articles even if he didn't create them. If you don't give him permission, allowed() method will check if he created that article. But it is working only with belongsTo relationship.

If you want to check if the logged user can edit user he is looking at, you can make simple if statement like this:

```php
@if(Auth::user()->id === $user->id)
   //
@endif
```
There's no need to check for permissions unless you have a admin which can edit all users.

Hope it helps.

There is a allowed method, have a look:

```php
/**
 * Check if the user is allowed to manipulate with entity.
 *
 * @param string $providedPermission
 * @param object $entity
 * @param bool $owner
 * @param string $ownerColumn
 * @return bool
*/
public function allowed($providedPermission, $entity, $owner = true, $ownerColumn = 'user_id');
```

**Comment by rusjoan** [comment]
As I have understood, permissions that attached to role doesn't provide entity check except such ones that attached directly to user. Am I right?

**Comment by romanbican** [comment]
No. They can be attached to role.
