### ISSUE TITLE
Revoke specific permission from user

### ISSUE THREAD

**Issue by rusjoan** [romanbican/roles#51]
Is there any chance to easily revoke specific permission from user?

Let's suppose that *user* has the role '**user**' which in turn has permissions to '**see.article**' and '**create.article**'.

So how to revoke 'create.article' permission from the specific user that has 'user' role?
I'm not sure about that it's really possible, maybe there's any other good workaround.

Thanks!

**Comment by sniper7kills** [comment]
I'm working on a fork that has this. While I wouldn't say its ready for production use, you should easily be able to look through the changes I've made to implement this.
https://github.com/DynamicCodeNinja/roles/tree/NestedRoles-DeniablePermissions

The two files you should look at from my fork are:
src/migrations/2015_02_09_132439_create_permission_user_table.php
src/Bican/Roles/Traits/HasRoleAndPermission.php

The main changes you will want to look at are in the getPermissions function.

**Comment by rusjoan** [comment]
Thanks, will look at this

**Comment by sniper7kills** [comment]
Don't know if you came up with a solution,  
But Check out #64
Hopefully it gets pulled, otherwise its just the matter of editing one file, and creating another.
