### ISSUE TITLE
Give more clear instructions for entity check

### ISSUE THREAD

**Issue by rusjoan** [romanbican/roles#53]
It's taken me a lot of time to totally understand the behavior of `allowed()` method that provides entity checks. Please, complete the docs with such a sentence that `allowed()` method doesn't look at user's attached permissions if it owns an entity (or smth like that).

As for me, logic of mentioned method isn't good enough.

**Comment by codeyash** [comment]
Submit a pull request with required doc changes. Author may accept. I'm not owner. Pure suggestion only.

**Comment by romanbican** [comment]
I'll update docs a little bit today after Laravel 5.1 release. I'll also release 2.0 version of this package.

**Comment by romanbican** [comment]
Hm, I think that the documention about allowed method is actually good. I don't know what should I change.
