### ISSUE TITLE
How do I rename table name?

### ISSUE THREAD

**Issue by coder77** [romanbican/roles#56]
Hello, my company has some prefix on the mysql table name. But it seem the table name is hardcorded in the HasRoleAndPermission trait:

    public function rolePermissions()
    {
        if (!$roles = $this->getRoles()->lists('id')->toArray()) { $roles = []; }

        return Permission::select(['permissions.*', 'permission_role.created_at as pivot_created_at', 'permission_role.updated_at as pivot_updated_at'])
                ->join('permission_role', 'permission_role.permission_id', '=', 'permissions.id')->join('roles', 'roles.id', '=', 'permission_role.role_id')
                ->whereIn('roles.id', $roles) ->orWhere('roles.level', '<', $this->level())
                ->groupBy('permissions.id');
    }

Is it possible to rename the default table name?

**Comment by romanbican** [comment]
Well, no, there isn't. But you can always overwrite this method by yourself.

**Comment by Kryptonit3** [comment]
@coder77 refer to this pull request I made - https://github.com/romanbican/roles/pull/57/files

**Comment by richstandbrook** [comment]
This is disappointing—I thought this library looked table/model agnostic. But it's really tightly coupled to the user model and table.
