### ISSUE TITLE
Interface 'Bican\Roles\Contracts\HasRoleAndPermission' not found

### ISSUE THREAD

**Issue by Wipsly** [romanbican/roles#58]
Hello,

I am using Laravel 5 and followed your instructions. Because of Laravel 5 I added these line to mal config/app.php

		'Bican\Roles\RolesServiceProvider',

Instead of:

 Bican\Roles\RolesServiceProvider::class,

And in my composer.json I used 1.7.*"

"require": {
		"laravel/framework": "5.0.*",
		"laravelcollective/html": "~5.0",
		"bican/roles": "1.7.*"
	},

I get the following error, when I try to visit my users index

Interface 'Bican\Roles\Contracts\HasRoleAndPermission' not found

**Comment by romanbican** [comment]
For Laravel 5 follow this documentation https://github.com/romanbican/roles/tree/1.7.1#install
