### ISSUE TITLE
Create roles 

### ISSUE THREAD

**Issue by Ethrios** [romanbican/roles#60]
Im new at laravel, i followed your instructions, but have no idea where to create the roles.  Do i need to make a new model "Roles" for that? or where?  Is it possible for you to make a simple example of it please? along with assigning a role to an user.  Thanks in advance.

**Comment by Kryptonit3** [comment]
@Ethrios look here

https://github.com/romanbican/roles/blob/master/README.md#creating-roles

**Comment by Ethrios** [comment]
Yeah, but what file is that? is it a Role.php model? or the User.php model? or a controller?  im lost here :/

**Comment by romanbican** [comment]
We can't teach you that here, sorry. There is a really good documentation on [Laravel.com](http://laravel.com/docs/5.1) and you can even watch videos on [Laracasts.com](http://laracasts.com).
