### ISSUE TITLE
Upgrade to Laravel 5.1 causing error in RolesServiceProvider.php line 47

### ISSUE THREAD

**Issue by Bulmer** [romanbican/roles#72]
FatalErrorException in RolesServiceProvider.php line 47:
Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()

any idea what may be causing this?

**Comment by romanbican** [comment]
You must also upgrade to `bican/roles 2.1.*`.

**Comment by Bulmer** [comment]
Ok, that was it. Also I see that 'HasRoleAndPermission' has replaced 'HasRoleAndPermissionContract'. All good now, thanks.
