### ISSUE TITLE
Middleware based on user level

### ISSUE THREAD

**Issue by ziming** [romanbican/roles#73]
Middleware based on user level, given how there are middlewares for roles and permissions.

**Comment by romanbican** [comment]
Good idea. I'm on it.

**Comment by ziming** [comment]
Thank you!

Another addition I would like to have would be I specify based on a particular role 'manager', let say level 2.

Then to access that page I need to be either of role 'manager' or a role level of 3 and above. Other roles that is of level 2 but not 'manager' couldn't access.

Thank you once again.

**Comment by romanbican** [comment]
VerifyLevel middleware has been added.
...
Well, you can create your own middleware for that.

**Comment by ziming** [comment]
Thank you, hmm is it fine to add blade extension for level too?

**Comment by romanbican** [comment]
Done!

**Comment by ziming** [comment]
Thank you.
