### ISSUE TITLE
Exceptions attributes

### ISSUE THREAD

**Issue by mix359** [romanbican/roles#83]
Hi,
I'm creating an error handler for the exceptions raised by roles, and I've noticed that in the exceptions there's only the pre compiled message, created in the constructor.
Would be awesome to have the raw data (permission, role or level) with an accessor function (like getPermission), so I can create custom message, based on this data, or make a localized message.

I really need it, because I've to localize my error messages, and at the moment I could not, because a full English error message is returned.
It should be easy to do, but if you need, I can do it and make a pull request ;)
Thanks

**Comment by romanbican** [comment]
Hi, feel free to make a PR.
