### ISSUE TITLE
Too many redirects?

### ISSUE THREAD

**Issue by zlorkovic** [romanbican/roles#84]
Hi,

Don't know can anybody reproduce this error or is this due some bad configuration on my laravel, but, I have routes like this

Route::group(['middleware' => 'role:parent'], function()
{
	Route::get('parent', 'ParentController@index');
	Route::get('parent/invoices', 'ParnetController@invoices');
});

Everything works fine expect when I'm on url for example http://mydomain.com/parent/invoices and leave it open for few hours (until session expires). Then I refresh page, i got browser error that there were too many redirect and that browser cannot display page.

If I got to root of site and login as "parent", everything works fine again.

Is this due some redirects in role middleware or something else?

**Comment by zlorkovic** [comment]
I just found out that before my browser throws too many redirects error my error log fills with messages like this

 local.ERROR: exception 'Bican\Roles\Exceptions\RoleDeniedException' with message 'You don't have a required ['admin'] role.'

**Comment by romanbican** [comment]
Have a look at documentation. https://github.com/romanbican/roles#middleware
