### ISSUE TITLE
phpunit and pretend

### ISSUE THREAD

**Issue by shchekotiki** [romanbican/roles#85]
I am trying to test functionality involving Roles with phpunit, but none of the tests are working even though they should.  Why does this happen?  I have traced the problem down to getRoles returning an empty collection even though the role has been attached just fine. I get the sense that the pretend feature is supposed to fix this problem but am not sure how - could you explain the pretend feature more in the documentation?

Other than that I am finding this package very useful, thanks so much! :)

**Comment by romanbican** [comment]
It's because of caching. I'm working on a new version and there will be option to disable caching.

**Comment by shchekotiki** [comment]
Great, thanks!
