### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by matrunchyk** [romanbican/roles#86]
Hi Roman,

Could you please advice me how to check if role has a permission in blade?
It would be great to has something like $role->hasPermission($permission).

Thanks a lot for your package!

**Comment by romanbican** [comment]
Hello,
you can do it simply like this:

```php
$role->permissions->contains($permission);
```

**Comment by matrunchyk** [comment]
Wow, thanks a lot!

By the way, is it possible to use your package in annotation-style? Like:

```PHP
/**
 * @Middleware('permission:users.index')
 * @return \Illuminate\View\View
 */
public function index()
{
    $users = User::latest()->get();
    return view('users.index', compact('users'));
}
```

**Comment by romanbican** [comment]
It should work with annotation package, but I can't confirm that.
