### ISSUE TITLE
GROUP BY error on PostgreSQL

### ISSUE THREAD

**Issue by scmmmh** [romanbican/roles#88]
I'm runnning "bican/roles": "2.1.*" with "laravel/framework": "5.1.*" on PostgreSQL and when I use @permission in my templates I get the following error:

SQLSTATE[42803]: Grouping error: 7 ERROR: column "permission_role.created_at" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: select "permissions".*, "permission_role"."created_at" as "p...
^ (SQL: select "permissions".*, "permission_role"."created_at" as "pivot_created_at", "permission_role"."updated_at" as "pivot_updated_at" from "permissions" inner join "permission_role" on "permission_role"."permission_id" = "permissions"."id" inner join "roles" on "roles"."id" = "permission_role"."role_id" where 0 = 1 or "roles"."level" < 0 group by "permissions"."id") (View: resources/views/layout.blade.php) (View: resources/views/layout.blade.php)

The problem is in HasRoleAndPermission.php->rolePermissions() on line 165. The query selects all columns, but on the groupBy part only groups by permission id. I'm not quite sure which of the columns the remaining code needs, but those need to be added into the groupBy expression.

**Comment by scmmmh** [comment]
I've now done some further tests and by updating line 168 to

->groupBy([$prefix . 'permissions.id', 'pivot_created_at', 'pivot_updated_at']);

fixes the problem.

**Comment by niknetniko** [comment]
:+1:  for this

**Comment by gildniy** [comment]
Nice, to here u resolved it!

**Comment by allanolivei** [comment]
Insert this in repository, please.

**Comment by romanbican** [comment]
Done. Thanks.
