### ISSUE TITLE
Duplicate prefix on query rolePermissions

### ISSUE THREAD

**Issue by banobi** [romanbican/roles#89]
If I use a prefix of the database tables, the query on method rolePermissions (line 165 of HasRoleAndPermision.php) is generated with duplicated prefix.

I test with this change, and works:
```return $permissionModel::select(['permissions.*', 'permission_role.created_at as pivot_created_at', 'permission_role.updated_at as pivot_updated_at'])
            ->join('permission_role', 'permission_role.permission_id', '=', 'permissions.id')->join('roles', 'roles.id', '=', 'permission_role.role_id')
            ->whereIn('roles.id', $this->getRoles()->lists('id')->toArray()) ->orWhere('roles.level', '<', $this->level())
            ->groupBy('permissions.id');```

Best regards,
Vasco Cruz

(Sorry about my bad english)

**Comment by herzcthu** [comment]
Same issue with Laravel 5.1

**Comment by banobi** [comment]
I forgot to wrote, my test was to Laravel 5.1.

**Comment by herzcthu** [comment]
It seem Laravel add prefix automatic for all model database connection. 
If so, should delete all prefix assignment in HasRoleAndPermission.php trait.
on line 163, we have following line. I've commented out and assigned new empty string. This is just work around.
//$prefix = config('database.connections.' . config('database.default') . '.prefix');
$prefix = '';

**Comment by romanbican** [comment]
I removed it.
