### ISSUE TITLE
list of users at or under a certain level

### ISSUE THREAD

**Issue by hubentom** [romanbican/roles#98]
any easy way to get all users with same level or under (or greater for that matter) for a given level ... or even  by role such as all users containing a certain role or a role at equal or less in level

**Comment by httpoz** [comment]
I agree. Trying to wrap my head around this.

**Comment by httpoz** [comment]
aye @hubentom 
in Role model add
`public function users()`
  `{`
      `return $this->belongsToMany('App\User', 'role_user', 'role_id', 'user_id');`
 `}`

and then in your controller add:
`$admins = Role::find(1)->users;`

**Comment by hubentom** [comment]
that gets the users for a given role...? I need the users for a given LEVEL

**Comment by httpoz** [comment]
``` php
$level = Role::where('level', 1)->get();
$admins = $level->users;
```

**Comment by commandantp** [comment]
Can you add it in the code please ? Super useful to retrieve users with a role. 
Thanks.
